# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

google-ID: 'UA-112060364-2'

timezone: Europe/London

menu:
- {name: 'Portfolio', folder: 'pages', file: 'portfolio.html'}
- {name: 'Blog', folder: 'pages', file: 'blog.html'}
- {name: 'Contact', folder: 'pages', file: 'contact.html'}
- {name: 'About', folder: 'pages', file: 'about.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link: 'https://twitter.com/bexmakesgames'}
- {icon: 'instagram', link: 'https://instagram.com/bexmakesgames'}
- {icon: 'envelope', link: 'mailto:bexedmondson@gmail.com'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'Related Posts:'

post_date_prefix: 'Posted on'
